# Basic Worker configuration
name = "cloudflare-worker-error-page"
main = "worker.js"
compatibility_date = "2025-08-24"


# KV namespace to store maintenance state
kv_namespaces = [
  { binding = "MAINTENANCE_KV", id = "f7ed9defd85c4a168b7c351d5d49d663" }
]

[vars]

# Language setting (FR or EN)
LANGUAGE = "FR"

# For 503 errors when maintenance is activated
TEXT_MAINTENANCE_TYPE = "Maintenance serveur"
TEXT_MAINTENANCE_MESSAGE = "Je fais de nouvelles expériences !! \n Promis je me dépêche ! 😗"
TEXT_MAINTENANCE_GIF = "https://raw.githubusercontent.com/JamesDAdams/cloudflare-worker-error-page/refs/heads/main/assets/maintenance.gif"

# For 504 errors when internet connection is down
TEXT_BOX_ERROR_TYPE = "Erreur de connexion"
TEXT_BOX_ERROR_MESSAGE = "On dirait que ma box fibre et 4G ont décidé de faire une pause, il va falloir patienter... 😩 N’hésitez pas à me le signaler quand même !"
TEXT_BOX_ERROR_GIF = "https://raw.githubusercontent.com/JamesDAdams/cloudflare-worker-error-page/refs/heads/main/assets/box_error.gif"

# For 500 errors when server probably crashed
TEXT_GENERIC_ERROR_TYPE = "Erreur serveur"
TEXT_GENERIC_ERRORR_MESSAGE = "Le serveur a sûrement dû crash... N'hésitez pas à me le signaler !"
TEXT_GENERIC_ERROR_GIF = "https://raw.githubusercontent.com/JamesDAdams/cloudflare-worker-error-page/refs/heads/main/assets/generic_error.gif"

# For 503 errors when service is down
TEXT_CONTAINER_ERROR_TYPE = "Service indisponible"
TEXT_CONTAINER_ERROR_MESSAGE = "Service non démarré ou planté ! N’hésitez pas à me le signaler au cas où !"
TEXT_CONTAINER_ERROR_GIF = "https://raw.githubusercontent.com/JamesDAdams/cloudflare-worker-error-page/refs/heads/main/assets/container_error.gif"

# Enable or disable 4G banner functionality
ENABLE_4G_BANNER = true
# Message for 4G banner when fiber is down
TEXT_4G_BANNER_MESSAGE = "Attention des lenteurs peuvent survenir, ma fibre est H.S. Le serveur fonctionne en 4G !"

# You can enable the variables below or add them as secrets in Cloudflare

# Domain authorized to access maintenance button
# You can put your maintenance subdomain here or add it as a secret in the worker
# This will be the page to enable/disable maintenance
# MAINTENANCE_DOMAIN = "maintenance.domaine.fr"

# URL to check if Nginx Proxy Manager is accessible redirect to port 80 of your reverse proxy
# You can put your test subdomain here or add it as a secret in the worker
# NPM_HEALTH_URL = "https://test.domaine.fr"

# URL to check if origin server is accessible
# You can put your server IP here or add it as a secret in the worker
# ORIGIN_PING_URL = "YourServerIP"