# Configuration de base du Worker
name = "cloudflare-worker-error-page"
main = "worker.js"
compatibility_date = "2025-08-24"

# Namespace KV pour stocker l'état de maintenance
kv_namespaces = [
  { binding = "MAINTENANCE_KV", id = "f7ed9defd85c4a168b7c351d5d49d663" }
]

# Vous pouvez activer les variable ci-dessous ou les ajouter en tant que secrets dans Cloudflare
[vars]

TEXT_MAINTENANCE_TYPE = "Maintenance serveur TEST"
TEXT_MAINTENANCE_MESSAGE = "Je fais de nouvelles expériences !! \n Promis je me dépêche ! 😗"
TEXT_MAINTENANCE_GIF = "https://video-private-assets.canva.com/VAFj8I_yGVw/v/4bb77a0016.mp4?exp=1756131120000&cf-ck=GkEmAv8gD8BRKATE3I7M_s9Rh-rnF__Lew_LUl1uMt4&cf-sig=SvW4OqyHTvybbMq7f_2bEC5DtLxBiLS71FVGGbfzO9E&cf-sig-kid=CO7cCjZ_YiI=&sig=0SQnpq30A2NipD9A2CQmwfrtxPbrFDUdU6KMJcxUlZ8&sig-kid=GzFgFdhXD-Q="

# Domaine autorisé pour accéder au bouton de maintenance
# Vous pouvez mettre votre subdomaine de maintenance ici ou l'ajouter en tant que secret dans le worker
# Ce serra la page pour activer/desactiver la maintenance
# MAINTENANCE_DOMAIN = "maintenance.domaine.fr"

# URL pour vérifier si Nginx Proxy Manager est accessible rediriger le vers le 80 de votre reserse proxy
# Vous pouvez mettre votre subdomaine de test ici ou l'ajouter en tant que secret dans le worker
# NPM_HEALTH_URL = "https://test.domaine.fr"

# URL pour vérifier si le serveur d'origine est accessible 
# Vous pouvez mettre l'ip de votre serveur ici ou l'ajouter en tant que secret dans le worker
# ORIGIN_PING_URL = "IpDeVotreServer"